/**
 * Copyright since 2025 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

/**
 * Font Awesome icon name -> Material Symbols ligature.
 * Names already in Material Symbols form (e.g. 'settings') pass through via faToMaterial().
 *
 * Keep assets/styles/fa-compat.scss in sync when adding entries here.
 */
export const FA_MATERIAL_MAP: Record<string, string> = {
  add: 'add',
  'address-card': 'contact_page',
  anchor: 'anchor',
  archive: 'archive',
  'arrow-circle-right': 'arrow_circle_right',
  'arrow-down': 'arrow_downward',
  'arrow-left': 'arrow_back',
  'arrow-right': 'arrow_forward',
  'arrow-up': 'arrow_upward',
  'angle-down': 'expand_more',
  ban: 'block',
  bars: 'menu',
  bell: 'notifications',
  bolt: 'bolt',
  book: 'book',
  'book-open': 'menu_book',
  briefcase: 'work',
  bucket: 'category',
  building: 'domain',
  calculator: 'calculate',
  calendar: 'calendar_today',
  'calendar-alt': 'calendar_month',
  'calendar-check': 'event_available',
  camera: 'photo_camera',
  'caret-down': 'arrow_drop_down',
  'chart-bar': 'bar_chart',
  'chart-line': 'show_chart',
  'chart-pie': 'pie_chart',
  check: 'check',
  'check-circle': 'check_circle',
  'check-double': 'done_all',
  'chevron-down': 'expand_more',
  'chevron-left': 'chevron_left',
  'chevron-right': 'chevron_right',
  circle: 'circle',
  clock: 'schedule',
  close: 'close',
  cloud: 'cloud',
  'cloud-download-alt': 'cloud_download',
  'cloud-upload-alt': 'cloud_upload',
  code: 'code',
  'code-branch': 'account_tree',
  cog: 'settings',
  cogs: 'settings',
  coins: 'paid',
  'comment-alt': 'chat',
  comments: 'forum',
  copy: 'content_copy',
  dollar: 'attach_money',
  'dollar-sign': 'attach_money',
  donate: 'volunteer_activism',
  download: 'download',
  edit: 'edit',
  envelope: 'mail',
  exchange: 'swap_horiz',
  exclamation: 'priority_high',
  'exclamation-circle': 'error',
  'exclamation-triangle': 'warning',
  'external-link-alt': 'open_in_new',
  eye: 'visibility',
  'eye-slash': 'visibility_off',
  file: 'draft',
  'file-alt': 'description',
  'file-excel': 'table_view',
  'file-export': 'output',
  'file-invoice-dollar': 'request_quote',
  'file-pdf': 'picture_as_pdf',
  'file-upload': 'upload_file',
  'file-word': 'description',
  'fill-drip': 'format_color_fill',
  flag: 'flag',
  'folder-open': 'folder_open',
  globe: 'public',
  group: 'group',
  hashtag: 'numbers',
  'hand-holding-hand': 'handshake',
  'hand-holding-heart': 'volunteer_activism',
  'hand-holding-usd': 'paid',
  heart: 'favorite',
  'heart-broken': 'heart_broken',
  'heart-crack': 'heart_broken',
  home: 'home',
  'id-badge': 'badge',
  info: 'info',
  'info-circle': 'info',
  key: 'key',
  keyboard: 'keyboard',
  laptop: 'computer',
  'laptop-code': 'terminal',
  lightbulb: 'lightbulb',
  link: 'link',
  list: 'list',
  'list-ul': 'format_list_bulleted',
  'location-arrow': 'near_me',
  lock: 'lock',
  'lock-open': 'lock_open',
  minus: 'remove',
  'minus-circle': 'do_not_disturb_on',
  'money-bill': 'payments',
  'money-bill-alt': 'payments',
  'money-bill-wave': 'payments',
  'money-check': 'price_check',
  'money-check-dollar': 'request_quote',
  'not-equal': 'rule',
  pause: 'pause',
  pen: 'edit',
  'pen-nib': 'ink_pen',
  pencil: 'edit',
  'pencil-alt': 'edit',
  percent: 'percent',
  'piggy-bank': 'savings',
  play: 'play_arrow',
  plus: 'add',
  'plus-circle': 'add_circle',
  'power-off': 'power_settings_new',
  'question-circle': 'help',
  random: 'shuffle',
  receipt: 'receipt_long',
  repeat: 'repeat',
  road: 'route',
  rotate: 'autorenew',
  'sack-dollar': 'paid',
  save: 'save',
  search: 'search',
  'shield-alt': 'shield',
  'sign-out-alt': 'logout',
  sitemap: 'account_tree',
  'sticky-note': 'sticky_note_2',
  stop: 'stop',
  sync: 'sync',
  table: 'table_chart',
  'table-cells': 'grid_on',
  'tachometer-alt': 'dashboard',
  tag: 'sell',
  tags: 'sell',
  tasks: 'checklist',
  times: 'close',
  'times-circle': 'cancel',
  trash: 'delete',
  undo: 'undo',
  university: 'account_balance',
  unlink: 'link_off',
  upload: 'upload',
  user: 'person',
  'user-circle': 'account_circle',
  'user-shield': 'admin_panel_settings',
  'user-tie': 'badge',
  users: 'group'
};
